for file in src/components/admin/*.tsx; do
  sed -i -E 's/allUsers\.map/(allUsers || []).map/g' "$file"
  sed -i -E 's/businesses\.map/(businesses || []).map/g' "$file"
  sed -i -E 's/ngos\.map/(ngos || []).map/g' "$file"
  sed -i -E 's/donations\.map/(donations || []).map/g' "$file"
  sed -i -E 's/orders\.map/(orders || []).map/g' "$file"
  sed -i -E 's/listings\.map/(listings || []).map/g' "$file"
  sed -i -E 's/auditLogs\.map/(auditLogs || []).map/g' "$file"
  sed -i -E 's/ledgers\.map/(ledgers || []).map/g' "$file"
  sed -i -E 's/settlements\.map/(settlements || []).map/g' "$file"
  sed -i -E 's/unreadNotifs\.map/(unreadNotifs || []).map/g' "$file"
  sed -i -E 's/notifications\.map/(notifications || []).map/g' "$file"
  sed -i -E 's/roleAuditLogs\.map/(roleAuditLogs || []).map/g' "$file"
  sed -i -E 's/filteredUsers\.map/(filteredUsers || []).map/g' "$file"
  sed -i -E 's/reservations\.map/(reservations || []).map/g' "$file"
  sed -i -E 's/radiusAuditLogs\.map/(radiusAuditLogs || []).map/g' "$file"
  sed -i -E 's/filteredBusinesses\.map/(filteredBusinesses || []).map/g' "$file"
  sed -i -E 's/filteredNgos\.map/(filteredNgos || []).map/g' "$file"
done
